# Generated by Django 2.2.6 on 2020-12-11 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_auto_20201207_0139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='slug',
            field=models.SlugField(help_text='Slug группы должен быть уникальным и не превышать 100 символов', max_length=100, unique=True, verbose_name='Идентификатор группы'),
        ),
    ]
